### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by icanhazpython** [dalenewman/Transformalize#11]
Is it possible to run this tool on Linux? Perhaps with .net core? I'm interested in gathering data from a local Linux MySQL server, doing some transformations and de-normalization, then pushing it to another Linux server back into MySQL. Thanks!

**Comment by dalenewman** [comment]
While I have added a .net standard 2 target to many components, I haven't adapted the command line tool to run on .net core yet.

I'll leave this issue open until I do.

The OrchardCore.Transformalize module I'm working on *should* run cross platform, but I haven't tested it on a non-windows platform yet.  Regardless, it sounds like you would need the CLI.

**Comment by dalenewman** [comment]
I've [released](https://github.com/dalenewman/Transformalize/releases/tag/v0.8.30-beta) a new .NET Core based CLI that supports Linux.  I updated the [read me](https://github.com/dalenewman/Transformalize/blob/master/README.md) to demonstrate using it.
