### ISSUE TITLE
Transforming data to GeoJSON format

### ISSUE THREAD

**Issue by geezery** [dalenewman/Transformalize#2]
I have two fields (long,lat) in SQL Server and I have tried to transform those two fields to GeoJSON format, because I would like to use the bettermap panel with Kibana. I cannot figure out how to create such a transform from two fields and send it to the ElasticSearch.

http://www.elasticsearch.org/guide/en/kibana/current/_bettermap.html

**Comment by dalenewman** [comment]
I am so sorry.  I didn't see this issue.  By now, you've probably moved on, but here's how I do it...
Within the entity that has a latitude and longitude, I add this calculated field:

```xml
         <calculated-fields>
            <add name="LongLat" type="decimal">
              <transforms>
                <add method="csharp" script="return new[]{Longitude,Latitude};">
                  <parameters>
                    <add field="Longitude" />
                    <add field="Latitude" />
                  </parameters>
                </add>
              </transforms>
            </add>
          </calculated-fields>
```
