### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by eraser85** [dalenewman/Transformalize#3]
Hi,
does this project compile? On VS2015 U2 I'm unable to get quite a few dependencies via NuGet as it's not able to find them online:

  * Cfg-NET (required 0.7.4 - found 0.6.7)
  * Cfg-NET.Environment (req. 0.0.2 - found 0.0.1)
  * Cfg-NET.Reader (0.1.1 vs 0.1.0)
  * Cfg-NET.Shorthand (0.0.6 vs 0.0.4)
  * Common.Logging (3.3.1 vs 3.3.0 / Pre 3.3.2-Alpha3)
  * Quartz (2.3.3 vs 2.3.2)
  * System.Data.SQLite.Core (1.0.101 vs not found at all)

Any suggestion / clarification?

**Comment by dalenewman** [comment]
Sorry.  I had to publish the latest Cfg-NET libraries.  I was pointing to my local Nuget packages.  I'm not sure why Common.Logging, Quartz, and Systen.Data.SQLite.Core were problematic.  Please update and try building again.  Thanks.
