### ISSUE TITLE
Can't find TFL.exe

### ISSUE THREAD

**Issue by chrisrusu** [dalenewman/Transformalize#4]
Hi,

Great project, but where is TFL.exe located? 
Also, building Pipeline.Command crashes the CSC due to IOException.

Thanks.

**Comment by dalenewman** [comment]
I will try cloning and building on another computer to try and reproduce this.  I will also compile everything and put it in an updated release (which will include tfl.exe).  Thanks for reporting this.

**Comment by dalenewman** [comment]
Here [release 2](https://github.com/dalenewman/Transformalize/releases/tag/v0.0.2-beta).  It has compiled binaries for x86 and x64.

Hey @chrisrusu, I was wondering what version of Visual Studio you're using?

Thanks

**Comment by chrisrusu** [comment]
Got it, looks like the exe got flagged and removed by threat software. But I see it now. How are you building tfl.exe?

**Comment by dalenewman** [comment]
I am using Visual Studio 2015 Pro.  Just using the menu to do a rebuild all.   Note: there is one nuget package using a special feed, see bottom of readme for URL.

**Comment by dalenewman** [comment]
It's possible I have things missing due to git ignore.  I will know more once I try to clone and build on something other than my main dev laptop.

**Comment by dalenewman** [comment]
Hey @chrisrusu I wanted to let you know I haven't forgot about this issue.  I am working on getting continuous integration setup for Transformalize (to build and run tests on check-in).  Hopefully, overcoming any obstacles presented by a remote build server will clear up any build problems experienced by others (including you :-)
