### ISSUE TITLE
mapping

### ISSUE THREAD

**Issue by JackWangCUMT** [dalenewman/Transformalize#5]
How to mapping input table field to output table field?

**Comment by dalenewman** [comment]
Unlike traditional ETL systems, Transformalize's output can not be a pre-existing table.  So, it does not support a mapping from one table to another. Instead, Transformalize creates the output according to a convention.  Data still goes from and input table to an output table, but Transformalize decides how to create and update the output table.

Consider this configuration:

```xml
<cfg name="InputToOutput">

	<connections>
		<!-- this is my input; a local SQL Server database called InputDb -->
		<add name="input" provider="sqlserver" server="localhost" database="InputDb" />
		<!-- this is my output; a local SQL Server database called OutputDb -->
		<add name="output" provider="sqlserver" server="localhost" database="OutputDb" />
	</connections>
	
	<entities>
		<!-- This entity's name is "Colors" 
		     it corresponds to a table in InputDb -->
		<add name="Colors">
			<fields>
				<add name="Code" />
				<!-- the name is the InputDb's field name,
				     if you want the OutputDb's name to be different,
					 give it an alias, like below -->
				<add name="Name" alias="ColorName" />
				<add name="Hex" />
				<add name="Red" type="int" />
				<add name="Green" type="int" />
				<add name="Blue" type="int" />
			</fields>
		</add>
	</entities>
	
</cfg>
```

The configuration only describes the input.  When you run it for the first time, run it in init mode (with -minit).  You'd run the above configuration like this:

```bash
tfl -a InputToOutput.xml -minit
```

Here is what the input and output looks like afterwards in SQL Server Management Studio:

![ssms_2017-03-17_09-35-45](https://cloud.githubusercontent.com/assets/933086/24045464/9b492684-0af5-11e7-8a64-dd048ce58c11.png)

A subsequent run (without the -minit flag) would create a hashcode from the input, check it against the `TflHashCode` field in the output, and not make any changes to the output.

To reiterate, Transformalize does not allow mapping from one table to another (pre-existing) table.  Instead, it creates and updates the output in any number of providers (i.e. sql server, mysql, postgres, sqlite, sqlce, elasticsearch, lucene, or file).

Thank you for the question.

Dale

**Comment by JackWangCUMT** [comment]
Thanks
