### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [dalenewman/Transformalize#6]
Hello @dalenewman , I am a graphic designer and i like to contribute to open source software. So i designed a logo for transformalize. I tried to represent the function of the application. I used a load, a conversion symbol, and the letter t. Any other ideas? What do you think? I will wait for feedback.

Have a nice day.

![trans](https://user-images.githubusercontent.com/36298335/43199296-269acb5c-901a-11e8-8fe8-856020e8f65e.jpg)

**Comment by dalenewman** [comment]
I can add it to the read me and give you credit.  How would you like me to word the credit text / link?
