### ISSUE TITLE
Some questions about features

### ISSUE THREAD

**Issue by ZlobnyiSerg** [dalenewman/Transformalize#7]
Hi Dale. You solution seems to be most close to my ideas about how ETL should be looked like :)

I have couple of questions:
1. Are star-schema warehouses supported by Transformalize? When I have many sources loading data into single table?
2. Is is posstible to handle incremental updates by multiple columns? Is it ok to specify primary-key attribute on multiple columns?
3. Is it possible to handle time-based incremental updates? For example we can have lot of historical data we'd like to exclude from update, because we're sure it can't be changed. It would be great to have option to add some 'date-of-origin' attribute and ability to specify that we not going to update data before some date?

Thank you.

**Comment by dalenewman** [comment]
Thank you!

1.  Yes.  Each entity may have a different data source.  You can add as
many connections as necessary and specify which one to use with the
connection attribute.

2. Yes it is okay to specify primary key on multiple columns.  The columns
not marked as primary key are ones that would be updated (if they change).

3. Yes.  You can use a date time field as a version.  Moreover, an entity
may have a filter collection which is made up of elements that define
criteria with field, operator, and value attributes, or an expression
attribute that could be used to filter out data that you don’t want to
update.

Dale
