### ISSUE TITLE
Can I to use tfl in Visual Code in Ubuntu ?

### ISSUE THREAD

**Issue by rstoever** [dalenewman/Transformalize#9]
Hi

Can I to use tfl in Visual Code in Ubuntu ?

**Comment by dalenewman** [comment]
Unfortunately not.  Currently the CLI only runs on Windows.  Maybe some day though.

**Comment by dalenewman** [comment]
I've [released](https://github.com/dalenewman/Transformalize/releases/tag/v0.8.30-beta) a new .NET Core based CLI that supports Linux.  I updated the [read me](https://github.com/dalenewman/Transformalize/blob/master/README.md) to demonstrate using it.
